<?php
$labels = array();
$labels['devidentify_avatar_plugin'] = 'Contactes Dev Identify';
$labels['devidentify_avatar_use_gravatar'] = 'Utilitzar Gravatar';
$labels['devidentify_avatar_size'] = 'Mida del avatar (px)';
$labels['devidentify_avatar_rating'] = 'Puntuació del avatar';
$labels['devidentify_avatar_google_use'] = 'Utilitzar Google';
$labels['devidentify_avatar_G'] = 'G';
$labels['devidentify_avatar_PG'] = 'PG';
$labels['devidentify_avatar_R'] = 'R';
$labels['devidentify_avatar_X'] = 'X';
$labels['devidentify_avatar_use_custom'] = 'Utilitzar API definida';
