<?php
//Translation by Malte Kiefer (@beli3ver)
$labels = array();
$labels['devidentify_avatar_plugin'] = 'Dev Identify Adressbuch';
$labels['devidentify_avatar_use_gravatar'] = 'Gravatar nutzen';
$labels['devidentify_avatar_size'] = 'Avatar Größe (px)';
$labels['devidentify_avatar_rating'] = 'Avatar Einstufung';
$labels['devidentify_avatar_google_use'] = 'Google nutzen';
$labels['devidentify_avatar_G'] = 'G Einstufung';
$labels['devidentify_avatar_PG'] = 'PG Einstufung';
$labels['devidentify_avatar_R'] = 'R Einstufung';
$labels['devidentify_avatar_X'] = 'X Einstufung';
$labels['devidentify_avatar_use_custom'] = 'Benutze definiert API';
