<?php
$labels = array();
$labels['devidentify_avatar_plugin'] = 'Dev Identify Address Book';
$labels['devidentify_avatar_use_gravatar'] = 'Use Gravatar';
$labels['devidentify_avatar_size'] = 'Avatar size (px)';
$labels['devidentify_avatar_rating'] = 'Avatar rating';
$labels['devidentify_avatar_google_use'] = 'Use Google';
$labels['devidentify_avatar_G'] = 'G rated';
$labels['devidentify_avatar_PG'] = 'PG rated';
$labels['devidentify_avatar_R'] = 'R rated';
$labels['devidentify_avatar_X'] = 'X rated';
$labels['devidentify_avatar_use_custom'] = 'Use custom avatar API';
