<?php
$labels = array();
$labels['devidentify_avatar_plugin'] = 'Contactos Dev Identify';
$labels['devidentify_avatar_use_gravatar'] = 'Usar Gravatar';
$labels['devidentify_avatar_size'] = 'Tamaño del avatar (px)';
$labels['devidentify_avatar_rating'] = 'Puntuación del avatar';
$labels['devidentify_avatar_google_use'] = 'Usar Google';
$labels['devidentify_avatar_G'] = 'G';
$labels['devidentify_avatar_PG'] = 'PG';
$labels['devidentify_avatar_R'] = 'R';
$labels['devidentify_avatar_X'] = 'X';
$labels['devidentify_avatar_use_custom'] = 'Usar API definida';
