<?php
//Translation by Jérôme Dubois
$labels = array();
$labels['devidentify_avatar_plugin'] = 'Carnet d\'adresses Dev Identify';
$labels['devidentify_avatar_use_gravatar'] = 'Utiliser Gravatar';
$labels['devidentify_avatar_size'] = 'Taille des avatars (en pixels)';
$labels['devidentify_avatar_rating'] = 'Classement des avatars';
$labels['devidentify_avatar_google_use'] = 'Utiliser Google';
$labels['devidentify_avatar_G'] = 'Tout public (G)';
$labels['devidentify_avatar_PG'] = 'Public accompagné (PG)';
$labels['devidentify_avatar_R'] = 'Public restreint (R)';
$labels['devidentify_avatar_X'] = 'Public adulte (X)';
$labels['devidentify_avatar_use_custom'] = 'Utiliser l\'API définie';
